title: Hello, world! I'm LAM MINH HY
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ":title/"
baseurl: ''
url: https://sapiens-code.github.io
domain: sapiens-code.github.io
site-twitter: 

author: Lâm Minh Hy
author-img: my_avata.jpg
about-author: I am a software developer. Love technology, exercise and music. Always
  hungry to keep learning.
social-twitter: 
social-facebook: lam.hyminh
social-github: sapiens-code
social-linkedin: hy-lam
social-email: lamminhhy9999@gmail.com

discus-identifier: mr-brown

analytics: 

markdown: kramdown

plugins:
- jekyll-sitemap
- jekyll-paginate
- jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
