title: Hello, world! I'm LAM MINH HY
description: mình là Lâm Minh Hy, đây là trang blog cá nhân của mình, viết về mọi thứ mình quan tâm đến, đây như một khu vườn yên tĩnh của mình.
tagline: đây là một blog của Lâm Minh Hy
permalink: ":title/"
baseurl: ''
url: https://www.thesapiencode.com
domain: www.thesapiencode.com
site-twitter: 

author: Lâm Minh Hy
author-img: my_avata.jpg
about-author: I am a software developer. Love technology, exercise and music. Always
  hungry to keep learning.
social-twitter: 
social-facebook: lam.hyminh
social-github: sapiens-code
social-linkedin: hy-lam
social-email: lamminhhy9999@gmail.com

discus-identifier: mr-brown

analytics: 

markdown: kramdown

plugins:
- jekyll-sitemap
- jekyll-paginate
- jemoji
- jekyll-seo-tag

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
